### ISSUE TITLE
APP_KEY & DB_DATABASE as environment variable for scaling

### ISSUE THREAD

**Issue by likentong** [bitnami/bitnami-docker-dreamfactory#10]
Add in APP_KEY and DB_DATABASE as environment variable for scaling?
http://blog.dreamfactory.com/scaling-dreamfactory-with-docker

**Comment by dbarranco** [comment]
Hi @liken85 

Thank you so much for the feedback, we appreciate it so much :) 
I have opened an internal ticket in order to discuss this feature of the nami module, as soon as we have any update I will update this post.

Best regards!

**Comment by tvarsis** [comment]
Any update on this? The APP_KEY is vital to be able to set as environment variable to be able to restore/migrate DBs.

**Comment by tvarsis** [comment]
I tested this now, and it does pick up all the docker varibles that you provide in the docker-compose like this:

```
  dreamfactory:
    image: dreamfactorysoftware/df-docker:latest
    environment:
      - APP_KEY=base64:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
      - DF_JWT_TTL=180
      - DF_DB_MAX_RECORDS_RETURNED=50000

```
This is undocumented though, so documentation should be more clear on that is how it works.
