### ISSUE TITLE
Unable to run DF from docker, with host directories mounted as data volumes

### ISSUE THREAD

**Issue by CoruNethron** [bitnami/bitnami-docker-dreamfactory#11]
**Description**

I'm unable to run DreamFactory from docker image, with host directories mounted as data volumes.

**Steps to reproduce the issue:**

1. Precreate some directories:
```
cd /root/dftest
mkdir dreamfactory_data
mkdir mariadb_data
mkdir mongodb_data
mkdir redis_data
```

2. Create docker-compose.yml with the folowwing contents:
```
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/root/dftest/mariadb_data:/bitnami'
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/root/dftest/redis_data:/bitnami'
  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - '/root/dftest/mongodb_data:/bitnami'
  dreamfactory:
    image: 'bitnami/dreamfactory:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
      - redis
      - mongodb
    volumes:
      - '/root/dftest/dreamfactory_data:/bitnami'
```

3. Run: `docker-compose up -d`

**Describe the results you received:**

For a few minutes I can see:

![screenshot_5](https://user-images.githubusercontent.com/4215824/35869979-30140902-0bac-11e8-97b1-40107bc1b7eb.png)

Then: ERR_CONNECTION_REFUSED

**Describe the results you expected:**

DreamFactory app up and running. Accessible from web browser.

**Additional information you deem important (e.g. issue happens only occasionally):**

You can see, that mariadb and redis containers was up for about one minute and then exited with error.

```
docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                      PORTS               NAMES
90430e3450dc        bitnami/dreamfactory:latest   "/app-entrypoint.s..."   7 minutes ago       Exited (1) 38 seconds ago                       dftest_dreamfactory_1
0cf8ca761914        bitnami/mariadb:latest        "/app-entrypoint.s..."   7 minutes ago       Exited (1) 6 minutes ago                        dftest_mariadb_1
6bccbc872e9d        bitnami/redis:latest          "/app-entrypoint.s..."   7 minutes ago       Exited (1) 6 minutes ago                        dftest_redis_1
7b989ffb259e        bitnami/mongodb:latest        "/app-entrypoint.s..."   7 minutes ago       Up 7 minutes                27017/tcp           dftest_mongodb_1
```

Also, before this test i successfully run DreamFactory from docker image WITHOUT host directories mounted as data volumes (with default docker-compose.yml). But i was unable to create new folder within DreamFactory file manager, so decided to mount host directories as data volumes.

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 11
 Running: 8
 Paused: 0
 Stopped: 3
Images: 49
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 138
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-78-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990.6MiB
Name: ip-CENSORED
ID: G4DP:5HX3:GFV2:PXE2:VORQ:HMQ6:OBOE:55MA:GWMK:CSKV:STEG:7F3C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: corunethron
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

AWS, x86_64, Ubuntu 16.04
